### ISSUE TITLE
fails with selector option

### ISSUE THREAD

**Issue by sibsfinx** [sindresorhus/pageres#176]
```pageres yeoman.io 1366x768 --selector '.page-header'```

```
/usr/local/lib/node_modules/pageres/cli.js:54
			throw new Error(chalk.red('✗ ' + err.message));
			      ^
Error: ✗ PhantomJS exited with return value 1
    at /usr/local/lib/node_modules/pageres/cli.js:54:10
    at callback (/usr/local/lib/node_modules/pageres/node_modules/each-async/each-async.js:54:12)
    at /usr/local/lib/node_modules/pageres/node_modules/each-async/each-async.js:23:7
    at callback (/usr/local/lib/node_modules/pageres/node_modules/each-async/each-async.js:54:12)
    at /usr/local/lib/node_modules/pageres/node_modules/each-async/each-async.js:23:7
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pageres/node_modules/webshot/lib/webshot.js:201:9)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
```

**Comment by sibsfinx** [comment]
btw, `pageres yeoman.io 1366x768 --selector 'body'` works

**Comment by kevva** [comment]
```sh
$ pageres yeoman.io 1366x768 --selector '.page-header'

✔ Generated 1 screenshot from 1 url and 1 resolution
```

Make sure you're on the latest version. Looking at this line `at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pageres/node_modules/webshot/lib/webshot.js:201:9)` it makes me think you're using an older version.

**Comment by sibsfinx** [comment]
@kevva Thanks! `rm -rf` helped. Looks like it's because npm haven't updated modules
