### ISSUE TITLE
callback() can only be called once 

### ISSUE THREAD

**Issue by sud201449** [sindresorhus/pageres#182]
Getting error if we used to run with multiple sources(more than 10) 

```javascript
pageres\node_modules\each-async\node_modules\onetime\index.js:15
                               throw new Error(fnName + ' can only be called once.');
                                     ^
Error: callback() can only be called once.
   at C:\Projects\screencomparemay7\node_modules\pageres\node_modules\each-async\node_modules\onetime\index.js:15:11
   at callback (C:\Projects\screencomparemay7\node_modules\pageres\node_modules\each-async\index.js:33:4)
   at C:\Projects\screencomparemay7\node_modules\pageres\node_modules\each-async\node_modules\onetime\index.js:20:12
   at next (C:\Projects\screencomparemay7\node_modules\pageres\node_modules\rimraf\rimraf.js:71:7)
   at CB (C:\Projects\screencomparemay7\node_modules\pageres\node_modules\rimraf\rimraf.js:107:9)
   at C:\Projects\screencomparemay7\node_modules\pageres\node_modules\rimraf\rimraf.js:163:7
   at Object.oncomplete (fs.js:107:15)
nodemon] app crashed - waiting for file changes before starting...
'''

**Comment by sud201449** [comment]
in util .js i have put console log


```javascript
write.on('error', function (err) {
			     console.log("error on write",err);
				end(next.bind(null, err));
			});


error on write { [Error: EPERM, rename 'C:\Projects\screencomparemay7\public\modules\baselines\img\baselinescreens\module18-.marketIndices.module.png']
  errno: 50,
  code: 'EPERM',
  path: 'C:\\Projects\\screencomparemay7\\public\\modules\\baselines\\img\\baselinescreens\\module18-.marketIndices.module.png' }

```

**Comment by kevva** [comment]
`code: 'EPERM'` means that there is a permisson issue.

**Comment by sud201449** [comment]
Looks like issue with fs-write-stream-atomic ,
       i have modified fs.chown to sync , its working fine in windows.
```javascript
 fs.chownSync(this.__atomicTmp, uid, gid)
     moveIntoPlace.call(this, cb)
 /*  return fs.chownSync(this.__atomicTmp, uid, gid, function (er) {
      if (er) return cb(er)
      moveIntoPlace.call(this, cb)
   }.bind(this))*/

```

**Comment by kevva** [comment]
It's not an issue with `fs-write-stream-atomic`, you have permissions issues.
