### ISSUE TITLE
npm ERR! EACCES, unlink

### ISSUE THREAD

**Issue by Blumed** [sindresorhus/pageres#187]
Today updated my Pageres and it broke as soon I tried to use it. Like so:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
Cullans-MacBook-Pro:~ Master$ pageres http://www.sleepnumber.com 960x900

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```
Then I tried to uninstalling reinstalling the app. I had another error that I didn't save that made it look like it was failing at Phantomjs, but it wasn't. I ended up fallowing the instructions and installing Phantomjs manually and that gave me the brand new error:
```
npm http GET https://registry.npmjs.org/pageres
npm http 304 https://registry.npmjs.org/pageres
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/pageres/cli.js'
npm ERR! error rolling back  pageres@1.4.0 { [Error: EACCES, unlink '/usr/local/lib/node_modules/pageres/cli.js']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/pageres/cli.js' }
npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/pageres/cli.js'
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/pageres/cli.js']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/pageres/cli.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--global" "pageres"
npm ERR! cwd /Users/Master
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /usr/local/lib/node_modules/pageres/cli.js
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/local/lib/node_modules/pageres/cli.js'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Master/npm-debug.log
npm ERR! not ok code 0
```
So, I went here `/usr/local/lib/node_modules/pageres/cli.js` and deleted everything in Pageres and entered `npm install --global pageres` and it worked. I am on a Mac and running Yosemite, and yes ruby and node are installed correctly. Hope I save someone 20 minutes of they're lives. Also Sindresorhus, I use a lot of the tools you help develop, and I just wanted to say thanks for your time and efforts. I see you helping a ton of people with a wide assortment of issues on github and it is inspiring. Keep up the great work.

**Comment by kevva** [comment]
Thanks for you guide :).
