### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by crstauf** [sindresorhus/pageres#188]
okay so admittedly, I'm not all that familiar with node/npm, so I could be missing something simple. here's the command and output:

```
$ pageres google.com 1024x768 --verbose
/usr/local/lib/node_modules/pageres/cli.js:98
				throw err;
				      ^
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at module.exports (/usr/local/lib/node_modules/pageres/node_modules/screenshot-stream/node_modules/phantom-bridge/index.js:18:9)
    at module.exports (/usr/local/lib/node_modules/pageres/node_modules/screenshot-stream/index.js:28:11)
    at Pageres.exports.create (/usr/local/lib/node_modules/pageres/lib/util.js:148:15)
    at Pageres.<anonymous> (/usr/local/lib/node_modules/pageres/index.js:113:26)
    at Array.forEach (native)
    at Pageres.<anonymous> (/usr/local/lib/node_modules/pageres/index.js:109:9)
    at Immediate.immediate._onImmediate (timers.js:409:16)
```

`$ node -v` `v0.12.4`
`$ npm -v` `2.11.1`

should i uninstall everything and re-install?

any help on getting this fixed would be great; really thankful and enjoy this awesome script!

**Comment by kevva** [comment]
`EACCESS` is a permission issue. Follow this guide and reinstall `pageres`, https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md.
