### ISSUE TITLE
PhantomJS crashing while fetching screenshots in a for loop

### ISSUE THREAD

**Issue by rahul-desai3** [sindresorhus/pageres#201]
Here is what my code looks like:

```
// get screenshots for all url_from fields
for(var i=0; i<body.refpages.length; i++){

    pageres = new Pageres()
        .src(body.refpages[i].url_from, ['1024x1024'], {filename: body.refpages[i].url_from.match(/^(http)?s?:?(\/\/)?(www\.)?([a-zA-Z0-9\-\.\_]+\.?[a-zA-Z\.]*)\/?/)[4]})
        .dest('screenshots/');

    pageres.run(function (err) {
        if (err){
            console.error('Error: ');
            console.dir(err);
        }
        console.log('Got screenshot at: ' + Date.now());
    });
}
```
I get this error:

```
Error: 
{ [Error: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/7C40FD55-C3C8-4D6D-B691-DD82DADB16CF.dmp] noStack: true }
Got screenshot at: 1440544220904  // something that I log for every screenshot
/Users/rahul/backlink-checker/node_modules/pageres/node_modules/each-async/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				      ^
Error: callback() can only be called once.
    at /Users/rahul/backlink-checker/node_modules/pageres/node_modules/each-async/node_modules/onetime/index.js:15:11
    at callback (/Users/rahul/backlink-checker/node_modules/pageres/node_modules/each-async/index.js:38:4)
    at /Users/rahul/backlink-checker/node_modules/pageres/node_modules/each-async/node_modules/onetime/index.js:20:12
    at next (/Users/rahul/backlink-checker/node_modules/pageres/node_modules/rimraf/rimraf.js:72:7)
    at CB (/Users/rahul/backlink-checker/node_modules/pageres/node_modules/rimraf/rimraf.js:108:9)
    at /Users/rahul/backlink-checker/node_modules/pageres/node_modules/rimraf/rimraf.js:142:18
    at FSReqWrap.oncomplete (fs.js:95:15)
```
How do I fix this?

**Comment by rahul-desai3** [comment]
Also, for some URLs, I get this error:

```
{ [Error: Couldn't load url: http://sage.nowsprouting.com/waxahachiebiblechurch/resources/bible-reading/] noStack: true }

{ [Error: Couldn't load url: http://wbctx.org/resources/bible-reading/] noStack: true }
```

**Comment by SamVerschueren** [comment]
1. http://wbctx.org/resources/bible-reading/ is working as expected. Try upgrading to the latest `pageres` version.
2. http://sage.nowsprouting.com/waxahachiebiblechurch/resources/bible-reading/ is indeed not working. Probably because it's a flash website which was [dropped](http://phantomjs.org/supported-web-standards.html) a long time ago. Can someone confirm? (@sindresorhus @kevva)
3. I can only debug your initial error if you provide me with the urls you are using in that loop.

**Comment by sindresorhus** [comment]
Can you try upgrading to the latest version and see if it's still an issue?

**Comment by SamVerschueren** [comment]
Closing due to lack of response. Please reopen if you still experience the same issues.
