### ISSUE TITLE
TypeError: Cannot read property 'pipe' of undefined

### ISSUE THREAD

**Issue by rahul-desai3** [sindresorhus/pageres#202]
My code is same as in [issue #201](https://github.com/sindresorhus/pageres/issues/201).

For a different input of `body.refpages`, there are 229 snapshots to be fetched.

I get this error:

```
[TypeError: Cannot read property 'pipe' of undefined]
Got screenshot at: 1440546329515
/Users/rahul/backlink-checker/node_modules/pageres/node_modules/each-async/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				      ^
Error: callback() can only be called once.
    at /Users/rahul/backlink-checker/node_modules/pageres/node_modules/each-async/node_modules/onetime/index.js:15:11
    at Pageres.<anonymous> (/Users/rahul/backlink-checker/node_modules/pageres/index.js:119:3)
    at Immediate.immediate._onImmediate (timers.js:409:16)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
``` 

Any idea why?

**Comment by SamVerschueren** [comment]
Can you upgrade to the latest pageres version and try again?
