### ISSUE TITLE
Couldn't get any items

### ISSUE THREAD

**Issue by nicolas-raoul** [sindresorhus/pageres#207]
```
$pageres frameset.html 800x800 --filename screenshot

/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/memoize-async/index.js:91
        throw err;
              ^
Error: Couldn't get any items
    at /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/viewport-list/index.js:60:7
    at /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/viewport-list/node_modules/got/index.js:174:5
    at BufferStream.<anonymous> (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/viewport-list/node_modules/got/node_modules/read-all-stream/index.js:52:3)
    at BufferStream.EventEmitter.emit (events.js:117:20)
    at finishMaybe (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/viewport-list/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:502:14)
    at endWritable (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/viewport-list/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:512:3)
    at BufferStream.Writable.end (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/viewport-list/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:477:5)
    at Unzip.onend (_stream_readable.js:483:10)
    at Unzip.g (events.js:180:16)
    at Unzip.EventEmitter.emit (events.js:117:20)
```
pageres-cli 1.1.1  
Similar to old closed issue #121  
`frameset.html` is the same as shown at #206

**Comment by SamVerschueren** [comment]
Can you upgrade to the latest version? Cannot reproduce.

**Comment by SamVerschueren** [comment]
Closing this due to inactivity. Please reopen if you still experience the same issue.

**Comment by nicolas-raoul** [comment]
Same bug with 3.0.2:
```
$ pageres /tmp/frameset.html 800x800 --filename screenshot
TypeError: Cannot call method 'split' of null
    at mapDomain (punycode.js:89:21)
    at Object.toUnicode (punycode.js:441:10)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/node_modules/humanize-url/node_modules/normalize-url/index.js:57:29)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/node_modules/humanize-url/index.js:10:9)
    at module.exports (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/filenamify-url/index.js:10:20)
    at Pageres.create (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/util.js:388:39)
    at /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:137:33
    at Array.map (native)
    at Pageres.run$ (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:109:64)
    at tryCatch (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/babel-runtime/regenerator/runtime.js:72:40)
```
```
$ npm list -g pageres
/usr/local/lib
├── pageres@3.0.2 
└─┬ pageres-cli@2.0.0
  └── pageres@3.0.2 
$ npm list pageres
/home/nico
└── pageres@3.0.2
```

**Comment by nicolas-raoul** [comment]
Different error with 3.0.2:
```
$ pageres frameset.html 800x800 --filename screenshot
TypeError: Object #<Object> has no method 'isAbsolute'
    at Pageres.create (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/util.js:381:24)
    at /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:137:33
    at Array.map (native)
    at Pageres.run$ (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:109:64)
    at tryCatch (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/babel-runtime/regenerator/runtime.js:146:20)
    at /usr/local/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/babel-runtime/regenerator/runtime.js:191:11
```

**Comment by sindresorhus** [comment]
Upgrade Node.js.

**Comment by nicolas-raoul** [comment]
Indeed upgrading to NodeJS 5.2.0 fixed the problem! :-)

**Comment by atetc** [comment]
I upgraded to 7.7.2 but still have this error for 1536 × 2048 resolution
