### ISSUE TITLE
Error in example?

### ISSUE THREAD

**Issue by yoshyosh** [sindresorhus/pageres#219]
I copy pasted the example and am running into this issue, after performing `node start.js`. Any ideas?

```
/.../pageCapture/start.js:8
    .then(() => console.log('done'));
           ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3```
```
Here's what start.js looks like

```
const Pageres = require('pageres');

const pageres = new Pageres({delay: 2})
    .src('yeoman.io', ['480x320', '1024x768', 'iphone 5s'], {crop: true})
    .src('todomvc.com', ['1280x1024', '1920x1080'])
    .dest(__dirname)
    .run()
    .then(() => console.log('done'));
```

**Comment by sindresorhus** [comment]
Upgrade Node.js

**Comment by yoshyosh** [comment]
yikes, thanks!
