### ISSUE TITLE
grunt-pageres breaks: "ReferenceError: Map is not defined"

### ISSUE THREAD

**Issue by pixeline** [sindresorhus/pageres#234]
When trying to use grunt-pageres, I get a critical error: **ReferenceError: Map is not defined**

```
Registering "grunt-pageres" local Npm module tasks.
Reading /Users/pope/GITHUB/test-grunt-wp/node_modules/grunt-pageres/package.json...OK
Parsing /Users/pope/GITHUB/test-grunt-wp/node_modules/grunt-pageres/package.json...OK
Loading "pageres.js" tasks...ERROR
>> ReferenceError: Map is not defined
>>     at module.exports (/Users/pope/GITHUB/test-grunt-wp/node_modules/mem/index.js:36:41)
>>     at Object.<anonymous> (/Users/pope/GITHUB/test-grunt-wp/node_modules/pageres/dist/util.js:86:38)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/Users/pope/GITHUB/test-grunt-wp/node_modules/pageres/dist/index.js:189:51)
>>     at Module._compile (module.js:456:26)

````

**Comment by SamVerschueren** [comment]
Update NodeJS. Map is defined since 0.12.

**Comment by pixeline** [comment]
Thank you, that solved it!
