### ISSUE TITLE
If the first number is less than the second I get an error

### ISSUE THREAD

**Issue by ryanburnett** [sindresorhus/pageres#245]
I'm trying to capture an iPhone 5 screenshot. Landscape works but portrait throws an error.

```
pageres 1136x640 github.com
✔ Generated 1 screenshot from 1 url and 1 size
```
```
pageres 640×1136 github.com
Error: Couldn't get any items
    at /Users/Ryan/.npm/lib/node_modules/pageres-cli/node_modules/viewport-list/index.js:51:10
    at process._tickCallback (node.js:412:9)
```
```
pageres github.com 640×1136
RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/Ryan/.npm/lib/node_modules/pageres-cli/node_modules/got/index.js:52:21)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1258:8)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)
```

How can I avoid this error? Thank you!

I'm running:

- pageres 3.1.0
- npm 3.7.3
- node 5.9.0
- OS X 10.11.3

P.S. pageres is awesome!

**Comment by SamVerschueren** [comment]
It took me a while to figure out. The character you use in `640×1136` isn't the `x`-character, it's the multiplication sign http://unicode-table.com/en/#00D7. There is a slight difference between them.

```
×x
```

Type your command again without copy-pasting and it should work.

**Comment by ryanburnett** [comment]
D'oh! Thanks @SamVerschueren
