### ISSUE TITLE
Phantom JS EAGAIN issue

### ISSUE THREAD

**Issue by fahimk** [sindresorhus/pageres#255]
Error: spawn /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs EAGAIN
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Happening on heroku when I try to queue up multiple screenshots

**Comment by fahimk** [comment]
I was using async.each switching from that seems to solve the problem
