### ISSUE TITLE
Error: visitor for particular URL

### ISSUE THREAD

**Issue by richardkall** [sindresorhus/pageres#256]
When trying to capture **expressen.se** I get the following error (other URLs are fine):

```
{ Error: visitor : {
    at LineStream.<anonymous> (/Users/Richard/Projekt/X/node_modules/screenshot-stream/index.js:78:14)
    at emitOne (events.js:96:13)
    at LineStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at LineStream.Readable.push (_stream_readable.js:130:10)
    at LineStream.Transform.push (_stream_transform.js:128:32)
    at LineStream._pushBuffer (/Users/Richard/Projekt/X/node_modules/byline/lib/byline.js:123:17)
    at LineStream._transform (/Users/Richard/Projekt/X/node_modules/byline/lib/byline.js:114:8)
    at LineStream.Transform._read (_stream_transform.js:167:10)
    at LineStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at LineStream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7) noStack: true } } ]
```

Tried with both pageres and pageres-cli, same result.

Any ideas?

**Comment by kevva** [comment]
Could you run it with the `--verbose` flag?

**Comment by richardkall** [comment]
Thanks for replying quickly, this is what i get with the `--verbose` flag:

```
TypeError: Object is not a constructor (evaluating '{
ReferenceError: Can't find variable: rpx_params → about:blank on line 7 in function global code
TypeError: Object is not a constructor (evaluating '{
ReferenceError: Can't find variable: rpx_params → about:blank on line 7 in function global code
```

**Comment by SamVerschueren** [comment]
The same errors as in the debug console in Chrome.

<img width="813" alt="screen shot 2016-05-09 at 13 28 39" src="https://cloud.githubusercontent.com/assets/1913805/15111817/0019da60-15ea-11e6-92b6-a49546534907.png">

**Comment by richardkall** [comment]
Oh, I see them now as well. They didn't show up when I hade my adblocker on.

**Comment by kevva** [comment]
Could we just ignore all instances of `TypeError` etc. and render the page anyway maybe?

**Comment by SamVerschueren** [comment]
Can't we just ignore all page errors? We shouldn't care about them I guess.

**Comment by kevva** [comment]
Yeah, that's what I thought we were doing here https://github.com/kevva/screenshot-stream/blob/master/stream.js#L38-L40. But it seems like this is coming from somewhere else.

**Comment by SamVerschueren** [comment]
@kevva I tested it, it's actually [this](https://github.com/kevva/screenshot-stream/blob/master/stream.js#L60-L64) block that gets executed. So it looks like the status is `fail` on a page error.

**Comment by kevva** [comment]
So, that's a mystery. I thought that was only executed on network errors etc.

**Comment by SamVerschueren** [comment]
Might have found the issue. One sec :).

**Comment by SamVerschueren** [comment]
Reinstall pageres so it picks up the latest `screenshot-stream` and try again.

```
$ pageres expressen.se 1027x768

✔ Generated 1 screenshot from 1 url and 1 size
```

**Comment by richardkall** [comment]
Thanks! It works now!
