### ISSUE TITLE
Could not find or load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by Calinou** [sindresorhus/pageres#259]
I get this when running `pageres-cli minetest.net` on an Antergos (based on Arch Linux) system:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This application failed to start because it could not find or load the Qt platform plugin "xcb".
    at LineStream.<anonymous> (/usr/lib/node_modules/pageres-cli/node_modules/screenshot-stream/index.js:78:14)
    at emitOne (events.js:96:13)
    at LineStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at LineStream.Readable.push (_stream_readable.js:130:10)
    at LineStream.Transform.push (_stream_transform.js:128:32)
    at LineStream._pushBuffer (/usr/lib/node_modules/pageres-cli/node_modules/byline/lib/byline.js:123:17)
    at LineStream._transform (/usr/lib/node_modules/pageres-cli/node_modules/byline/lib/byline.js:114:8)
    at LineStream.Transform._read (_stream_transform.js:167:10)
    at LineStream.Transform._write (_stream_transform.js:155:12)
```

I already have `xcb` packages installed on my system, but I'm not sure if they're related.

**Comment by SamVerschueren** [comment]
Seems like PhantomJS wasn't properly installed. Can you remove `pageres-cli` and reinstall?

**Comment by Calinou** [comment]
> Seems like PhantomJS wasn't properly installed. Can you remove pageres-cli and reinstall?

I just tried (`npm uninstall -g pageres-cli` then `npm install -g pageres-cli`), without success. I get the same error.

**Comment by sindresorhus** [comment]
It's a problem with PhantomJS on your system. Not much we can do about it.

Try opening an issue at https://github.com/Medium/phantomjs
