### ISSUE TITLE
ReferenceError: Map is not defined

### ISSUE THREAD

**Issue by mansurali901** [sindresorhus/pageres#262]
Hi,
 I have Amazon Linux i have install npm using epel repository and after npm i have install pageres with npm install --global pageres-cli.
I already have a phantomjs version 1.9.8
nut when i tried to run pageres it giving me error.
/usr/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/mem/index.js:36
        memoized.__cache__ = opts.cache || new Map();
                                               ^
ReferenceError: Map is not defined
    at module.exports (/usr/lib/node_modules/pageres-cli/node_modules/pageres/node_modules/mem/index.js:36:41)
    at Object.<anonymous> (/usr/lib/node_modules/pageres-cli/node_modules/pageres/dist/util.js:452:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:213:48)
    at Module._compile (module.js:456:26)

I don't know how to fix this please let me know.

Regards,
Mansur

**Comment by SamVerschueren** [comment]
You're probably running on node 0.10 or 0.12. Upgrade to >=4.

**Comment by mansurali901** [comment]
Thanks Sam !
i fixed the issue with below steps.

[root@ifr4 ~]# wget https://raw.githubusercontent.com/creationix/nvm/v0.13.1/install.sh
[root@ifr4 ~]# chmod +x install.sh
[root@ifr4 ~]# ./install.sh
[root@ifr4 ~]# nvm list-remote
[root@ifr4 ~]# nvm install v0.12.0
[root@ifr4 ~]# nvm use v0.12.0

[root@ifr4 ~]# pageres google.com

✔ Generated 1 screenshot from 1 url and 1 size

**Comment by SamVerschueren** [comment]
I would suggest using node 4.4.7 LTS instead of 0.12. But that's up to you :).

**Comment by Raynos** [comment]
Adding node0.10 support would be nice...

**Comment by SamVerschueren** [comment]
And why is that? 0.10 is end of life.
