### ISSUE TITLE
C:\Program' is not recognized as a .. command

### ISSUE THREAD

**Issue by teachtyler** [sindresorhus/pageres#266]
```
Error: 'C:\Program' is not recognized as an internal or external command,
    at LineStream.<anonymous> (C:\Node\Repos\SimpleApi\node_modules\screenshot-stream\index.js:78:14)
    at emitOne (events.js:96:13)
    at LineStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at LineStream.Readable.push (_stream_readable.js:135:10)
    at LineStream.Transform.push (_stream_transform.js:128:32)
    at LineStream._pushBuffer (C:\Node\Repos\SimpleApi\node_modules\byline\lib\byline.js:125:17)
    at LineStream._transform (C:\Node\Repos\SimpleApi\node_modules\byline\lib\byline.js:116:8)
    at LineStream.Transform._read (_stream_transform.js:167:10)
    at LineStream.Transform._write (_stream_transform.js:155:12)
```

Most likely an issue with the location of my node install path, which is in C:\Program Files,
is there a way to fix without re-installing node?

**Comment by sindresorhus** [comment]
No need to post in multiple places. Especially not without cross-linking...

https://github.com/kevva/screenshot-stream/issues/35
