### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by billzt** [sindresorhus/pageres#283]
After installing pageres-cli, I try `pageres -d 10 todomvc.com`, but encounters error

```
/usr/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:31
class Pageres {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/pageres-cli/cli.js:13:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by SamVerschueren** [comment]
Upgrade to Node.js 4+.
