### ISSUE TITLE
UnboundLocalError: local variable 'req' referenced before assignment

### ISSUE THREAD

**Issue by xl7dev** [sindresorhus/pageres#296]
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1028:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1028:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1028:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)

**Comment by sindresorhus** [comment]
What is the problem? What caused the issue? Share some code.

**Comment by xl7dev** [comment]
I using python called pageres-cli,the Main code:
from multiprocessing.dummy import Pool as ThreadPool 
pool = ThreadPool(10)
results = pool.map(pageres_call_function, urls)
pool.close() 
pool.join()

**Comment by SamVerschueren** [comment]
This isn't getting us anywhere to be honest. If you want us to take a look at it, create the simplest example that fails on how you would call pageres from python.

**Comment by xl7dev** [comment]
cat urls.txt|xargs pageres

**Comment by xl7dev** [comment]
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/bin/phantomjs EAGAIN
    at exports._errnoException (util.js:1028:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3

**Comment by SamVerschueren** [comment]
Odd, that works perfectly fine for me.

```
http://www.google.com
```

```
$ cat urls.txt | xargs pageres
✔ Generated 1 screenshot from 1 url and 1 size
```

Try reinstalling/upgrading pageres first.

And please, for the 2nd time, add some explanation to your posts. The more info we have, the better we can help you but it has to come from both sides.

**Comment by kevva** [comment]
@xl7dev, are you still experiencing this issue?
