### ISSUE TITLE
Can't delete files/folders outside the current working directory.

### ISSUE THREAD

**Issue by sustained** [sindresorhus/pageres#306]
I keep getting this error.

```
Uncaught Promise Error:

Error: Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.
    at safeCheck (.../node_modules/del/index.js:19:9)
    at .../node_modules/del/index.js:35:5
    at Array.map (native)
    at .../node_modules/del/index.js:33:28
```

**Comment by kevva** [comment]
Are you running it with `.dest()` one/or more directories up?

**Comment by kevva** [comment]
What version are you running? This was fixed a long time ago.
