### ISSUE TITLE
Pageres-cli fails when SSL/Cert error

### ISSUE THREAD

**Issue by tresacton** [sindresorhus/pageres#373]
Whenever pageres-cli is supplied a target with an SSL or SSL Certificate error, it fails to capture a screenshot. 

Error:

`
Error: net::ERR_CERT_COMMON_NAME_INVALID at https://<redacted-ip-adderess>:443
tions (internal/process/task_queues.js:89:5)
  -- ASYNC --
    at Frame.<anonymous> (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/Page.js:629:49)
    at Page.<anonymous> (/usr/local/lib/node_modules/pageres-cli/node_modules/puppeteer/lib/helper.js:112:23)
    at captureWebsite (/usr/local/lib/node_modules/pageres-cli/node_modules/capture-website/index.js:145:13)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
`

I can't see any flags to ignore SSL errors/warnings, can you please advise?

**Comment by sindresorhus** [comment]
Try the latest version: https://github.com/sindresorhus/pageres/releases/tag/v7.0.0 It may have resolved the issue.

If not, open a new issue with an example URL so I can reproduce the problem.
