### ISSUE TITLE
p-map missing 6.2.0 (pageres-cli)

### ISSUE THREAD

**Issue by kingthorin** [sindresorhus/pageres#409]
I was using pageres-cli in a GitHub action. It started failing earlier today with the following stack
```console
HTTP request sent, awaiting response... internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'p-map'
Require stack:
- /opt/hostedtoolcache/node/13.14.0/x64/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js
- /opt/hostedtoolcache/node/13.14.0/x64/lib/node_modules/pageres-cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/13.14.0/x64/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js:23:14)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/hostedtoolcache/node/13.14.0/x64/lib/node_modules/pageres-cli/node_modules/pageres/dist/index.js',
    '/opt/hostedtoolcache/node/13.14.0/x64/lib/node_modules/pageres-cli/cli.js'
  ]
}
```

When I switched from `npm install -g pageres-cli` to:
```
npm install -g p-map
npm install -g pageres-cli
```

Everything works as expected.

This leads me to believe that pageres-cli uses the latest version of pageres for which 6.2.0 was released ~6hours ago.

**Comment by kingthorin** [comment]
![image](https://user-images.githubusercontent.com/7570458/110367189-5b568f00-8015-11eb-823c-4001323896be.png)
![image](https://user-images.githubusercontent.com/7570458/110367281-76c19a00-8015-11eb-807b-f0bddb1b3426.png)

**Comment by kingthorin** [comment]
Thanks, 6.2.1 seems to behave as expected.
