### ISSUE TITLE
My project works on windows server but not on my Ubuntu server. Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by bkmzci** [sindresorhus/pageres#431]
```
Error: Failed to launch the browser process!
[0721/193252.878073:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/apps/projectv/automation/screenshot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/root/apps/projectv/automation/screenshot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by sindresorhus** [comment]
The error says it all.

**Comment by bkmzci** [comment]
but the solution doesn't work or I don't know how to do it. How can I add a flag to chrome?

> The error says it all.

**Comment by bkmzci** [comment]
where do i add this code?
```
const browser = await puppeteer.launch({
  ignoreDefaultArgs: ['--disable-extensions'],
});
```

**Comment by bkmzci** [comment]
fixed:

```JS
new Pageres({ delay: 2,timeout:15,filename:urls[index],launchOptions: {args: ['--no-sandbox', '--disable-setuid-sandbox']} })
```
