### ISSUE TITLE
spawn EACCES Error

### ISSUE THREAD

**Issue by haohcraft** [sindresorhus/pageres#75]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

I got such errors by running "pageres todomvc.com yeoman.io 1366x768 1600x900"

any idea about that?? Thanks

**Comment by CarlosSouza** [comment]
Thanks!

But now I'm getting this error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

Do I need to install PhamtomJS manually?
